language: bash
sudo: false
before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz
  - tar xvf hugo_0.26_Linux-64bit.tar.gz
script:
  - ./hugo --theme=hugo-theme-casper
  - ls -l
  - ls -l public
after_script:
  - cd public
  - echo "www.witeaa.tk" > CNAME
  - git init
  - git config user.name "xjx00"
  - git config user.email "xjxyklwx@126.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - source
