BaseUrl= "http://blog.xjx00.ml/"
LanguageCode= "zh-CN"
Title= "Xjx00's Blog"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2017"
canonifyurls = true

[params]
  description = "欢迎访问我的个人博客"
  cover = "images/user.jpg"
  author = "xjx00"
  authorlocation = ""
  authorwebsite = "http://www.xjx00.ml/"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "xjx00"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
