BaseUrl= "http://www.witeaa.tk/"
LanguageCode= "zh-CN"
Title= "WIT电子爱好者协会"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2017"
canonifyurls = true
[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
  
[params]
  description = "WIT Electronic Amateur Association"
  cover = "images/cover.jpg"
  author = "witeaaer"
  authorlocation = ""
  authorwebsite = "http://www.witeaa.tk/"
  bio= "my bio"
  logo = "images/logo.png"
  #googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = ""
  #githubName = "xjx00"
  #twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  share = "false"
