BaseUrl= "http://www.witeaa.tk/"
LanguageCode= "zh-CN"
Title= "WIT电子爱好者协会"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2017"
canonifyurls = true
pluralizelisttitles = false
hasCJKLanguage = true
[[menu.main]]
  name = "最新动态"
  weight = 101
  url = "/news"
  
[[menu.main]]
  name = "Ideas"
  weight = 102
  url = "/diy"
  
[[menu.main]]
  name = "展示区"
  weight = 103
  url = "/show"
  
[[menu.main]]
  name = "下载中心"
  weight = 104
  url = "/download"
 
 [[menu.main]]
  name = "主页"
  weight = 100
  url = "/"
  
  [[menu.main]]
  name = "AboutUs"
  weight = 105
  url = "/about"
  

  
[params]
  description = "WIT Electronic Amateur Association"
  cover = "images/newyear.jpg"
  author = "witeaaer"
  authorlocation = ""
  authorwebsite = "http://www.witeaa.tk/"
  bio= "my bio"
  logo = "images/logobig.png"
  #googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = ""
  #githubName = "xjx00"
  #twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  share = "false"
